# Site
name: "Just a Recipe"
title: "Simply Recipe"
description: "Just a Recipe"
meta_description: "Only Recipes, no fluff!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: ''
disqus: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Chris:
    name: Chris
    display_name: Chris
    gravatar: 01e57ffa85f70be0feea622749e61108
    email: justarecipe@outlook.com
    web: https://justarecipe.github.io
    twitter: 
    description: ""

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
