---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _pages
  label: Site Pages
  create: all
  match: "**/*"
  templates:
  - post
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - main_posts
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - main_posts
upload_dir: assets/images
public_path: assets/images
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
