---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _pages
  label: Site Pages
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - main_posts
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - main_posts
upload_dir: assets/images
public_path: assets/images
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
